{
 "title": "Estació_masnou",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Humitat_sòl",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, soil_moisture, node \r\nFROM \"general_weather\" \r\nWHERE \"node\" = 'Masnou_Garden'\r\nAND time > now() - INTERVAL '15 minutes'\r\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Pressió_atmosfèrica",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 8, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, atmospheric_pressure, node \r\nFROM \"general_weather\" \r\nWHERE \"node\" = 'Masnou_Garden'\r\nAND time > now() - INTERVAL '15 minutes'\r\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Precipitació_acumulada",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, accumulated_rain, node \r\nFROM \"general_weather\" \r\nWHERE \"node\" = 'Masnou_Garden'\r\nAND time > now() - INTERVAL '15 minutes'\r\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Humitat_ambient",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, ambient_humidity, node \r\nFROM \"general_weather\" \r\nWHERE \"node\" = 'Masnou_Garden'\r\nAND time > now() - INTERVAL '15 minutes'\r\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Velocitat_vent",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 8, "y": 12 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, wind_speed, node \r\nFROM \"general_weather\" \r\nWHERE \"node\" = 'Masnou_Garden'\r\nAND time > now() - INTERVAL '15 minutes'\r\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Temperatura_ambient",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 13, "y": 12 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, ambient_temperature, node \r\nFROM \"general_weather\" \r\nWHERE \"node\" = 'Masnou_Garden'\r\nAND time > now() - INTERVAL '15 minutes'\r\nORDER BY time DESC"
    }
   ]
  }
 ]
}